In [55]:
import pandas as pd

df = pd.DataFrame({
    "Age": [22, 25, 28, 32, 35, 40],
    "Experience": [0, 2, 4, 7, 10, 15],
    "Salary": [25000, 35000, 50000, 70000, 90000, 120000]
})
df

   Age  Experience  Salary
0   22           0   25000
1   25           2   35000
2   28           4   50000
3   32           7   70000
4   35          10   90000
5   40          15  120000

In [57]:
from sklearn.model_selection import train_test_split

In [59]:
X=df[["Age","Experience"]]
y=df["Salary"]

In [61]:
X

   Age  Experience
0   22           0
1   25           2
2   28           4
3   32           7
4   35          10
5   40          15

In [63]:
y

0     25000
1     35000
2     50000
3     70000
4     90000
5    120000
Name: Salary, dtype: int64

In [29]:
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [31]:
X_train

   Age  Experience
5   40          15
2   28           4
4   35          10
3   32           7

In [33]:
X_test

   Age  Experience
0   22           0
1   25           2

In [35]:
y_train

5    120000
2     50000
4     90000
3     70000
Name: Salary, dtype: int64

In [37]:
y_test

0    25000
1    35000
Name: Salary, dtype: int64

In [39]:
import pandas as pd

data = {
    'Hours_Studied': [5, 7, 3, 8, 6],
    'Attendance': [85, 90, 70, 95, 80],
    'Marks': [75, 88, 55, 92, 80]
}


df = pd.DataFrame(data)
df

   Hours_Studied  Attendance  Marks
0              5          85     75
1              7          90     88
2              3          70     55
3              8          95     92
4              6          80     80

In [43]:
X=df[["Hours_Studied","Attendance"]]
y=df["Marks"]

In [45]:
X

   Hours_Studied  Attendance
0              5          85
1              7          90
2              3          70
3              8          95
4              6          80

In [47]:
y

0    75
1    88
2    55
3    92
4    80
Name: Marks, dtype: int64

In [65]:
from sklearn.model_selection import train_test_split

In [67]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [69]:
X_train

   Age  Experience
5   40          15
2   28           4
4   35          10
3   32           7

In [71]:
X_test

   Age  Experience
0   22           0
1   25           2

In [73]:
y_train

5    120000
2     50000
4     90000
3     70000
Name: Salary, dtype: int64

In [75]:
y_test

0    25000
1    35000
Name: Salary, dtype: int64