In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    "Age": [22, 25, 30, 35, 40, 45, 50, 55, 28, 32],
    "Glucose": [90, 110, 125, 140, 160, 170, 180, 190, 100, 130],
    "Diabetes": [0, 0, 0, 1, 1, 1, 1, 1, 0, 0]
})
df

   Age  Glucose  Diabetes
0   22       90         0
1   25      110         0
2   30      125         0
3   35      140         1
4   40      160         1
5   45      170         1
6   50      180         1
7   55      190         1
8   28      100         0
9   32      130         0

In [5]:
X=df[['Age','Glucose']]

In [10]:
y=df["Diabetes"]

In [12]:
X

   Age  Glucose
0   22       90
1   25      110
2   30      125
3   35      140
4   40      160
5   45      170
6   50      180
7   55      190
8   28      100
9   32      130

In [14]:
y

0    0
1    0
2    0
3    1
4    1
5    1
6    1
7    1
8    0
9    0
Name: Diabetes, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split

In [38]:
X_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=40,stratify=y)

In [40]:
X_train

   Age  Glucose
6   50      180
2   30      125
0   22       90
7   55      190
4   40      160
9   32      130
1   25      110
5   45      170

In [42]:
x_test

   Age  Glucose
8   28      100
3   35      140

In [44]:
y_train

6    1
2    0
0    0
7    1
4    1
9    0
1    0
5    1
Name: Diabetes, dtype: int64

In [46]:
y_test

8    0
3    1
Name: Diabetes, dtype: int64

In [50]:
print("training rows:",len(X_train))

training rows: 8

In [54]:
print("testing rows:",len(x_test))

testing rows: 2

In [56]:
print("Training class distribution")

Training class distribution

In [62]:
print(y_train.value_counts())

Diabetes
1    4
0    4
Name: count, dtype: int64

In [64]:
print("Testing class distribution")

Testing class distribution

In [66]:
print(y_test.value_counts())

Diabetes
0    1
1    1
Name: count, dtype: int64

In [ ]:
#data leakage

In [68]:
from sklearn.model_selection import train_test_split

In [72]:
from sklearn.preprocessing import StandardScaler

In [76]:
scaler=StandardScaler()

In [80]:
x_scaled=scaler.fit_transform(X)

In [84]:
X_train,X_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2,random_state=42)

In [ ]:
#-----best approach

In [90]:
from sklearn.model_selection import train_test_split

In [92]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [94]:
from sklearn.preprocessing import StandardScaler

In [96]:
scaler=StandardScaler()

In [108]:
x_train_scaled=scaler.fit_transform(X_train)
x_test_scaled=scaler.transform(X_test)

In [110]:
x_train_scaled

array([[ 0.61924038,  0.70523822],
       [-1.61488177, -1.87391869],
       [ 1.59059784,  1.35002744],
       [-0.83779581, -0.74553754],
       [-0.64352432, -0.58434024],
       [ 0.13356165,  0.3828436 ],
       [-0.35211708, -0.26194562],
       [ 1.10491911,  1.02763283]])

In [112]:
x_test_scaled

array([[-1.0320673 , -1.55152408],
       [-1.32347453, -1.22912946]])