In [2]:
import pandas as pd

df = pd.DataFrame({
    "Age": [20, 21, None, 22, 23],
    "Study_Hours": [3, 4, 2, None, 5],
    "Marks": [60, 75, 45, 80, 90]
})
df

    Age  Study_Hours  Marks
0  20.0          3.0     60
1  21.0          4.0     75
2   NaN          2.0     45
3  22.0          NaN     80
4  23.0          5.0     90

In [4]:
df.isnull()

     Age  Study_Hours  Marks
0  False        False  False
1  False        False  False
2   True        False  False
3  False         True  False
4  False        False  False

In [8]:
df.isnull().sum()

Age            1
Study_Hours    1
Marks          0
dtype: int64

In [10]:
df.isnull().sum().sum()

2

In [ ]:
#SimpleImputer

In [14]:
import pandas as pd

In [16]:
from sklearn.impute import SimpleImputer

In [18]:
df = pd.DataFrame({
    "Age": [20, 21, None, 22, 23],
    "Study_Hours": [3, 4, 2, None, 5]
})
df

    Age  Study_Hours
0  20.0          3.0
1  21.0          4.0
2   NaN          2.0
3  22.0          NaN
4  23.0          5.0

In [20]:
imputer=SimpleImputer(strategy="mean")

In [24]:
filled=pd.DataFrame(
    imputer.fit_transform(df),
    columns=df.columns,
    index=df.index
)
filled

    Age  Study_Hours
0  20.0          3.0
1  21.0          4.0
2  21.5          2.0
3  22.0          3.5
4  23.0          5.0

In [ ]:
data leakage in SimpleImputer

In [26]:
from sklearn.model_selection import train_test_split

In [30]:
from sklearn.impute import SimpleImputer

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [32]:
imputer=SimpleImputer(strategy="median")

In [ ]:
X_train_filled=imputer.fit_transform(X_train)

In [ ]:
X_test=imputer.transform(X_test)